export const ALL_PET_REQUEST = "ALL_PET_REQUEST";
export const ALL_PET_SUCCESS = "ALL_PET_SUCCESS";
export const ALL_PET_FAIL = "ALL_PET_FAIL";
export const CLEAR_ERR = "CLEAR_ERR";

export const PET_DETAILS_REQUEST = "PET_DETAILS_REQUEST";
export const PET_DETAILS_SUCCESS = "PET_DETAILS_SUCCESS";
export const PET_DETAILS_FAIL = "PET_DETAILS_FAIL";

export const USER_PET_REQUEST = "USER_PET_REQUEST";
export const USER_PET_SUCCESS = "USER_PET_SUCCESS";
export const USER_PET_FAIL = "USER_PET_FAIL";

export const REGISTER_PET_REQUEST = "REGISTER_PET_REQUEST";
export const REGISTER_PET_SUCCESS = "REGISTER_PET_SUCCESS";
export const REGISTER_PET_FAIL = "REGISTER_PET_FAIL";

export const BREED_INFO_REQUEST = "BREED_INFO_REQUEST";
export const BREED_INFO_SUCCESS = "BREED_INFO_SUCCESS";
export const BREED_INFO_FAIL = "BREED_INFO_FAIL";
